site_name: Jira Assistant
site_url: https://pypi.org/project/jira-assistant/
site_description: This website tells people how to fully use this package.
site_author: Sharry Xu
repo_url: https://github.com/SharryXu/jira-assistant
nav:
    - Home: index.md
    - About: about.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - powershell
plugins:
    - search:
        min_search_length: 3